name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v3

      # 2️⃣ Install Ruby 2.7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8

      # 3️⃣ Install Bundler
      - run: gem install bundler -v 2.3.26

      # 4️⃣ Install all gems from your Gemfile
      - run: bundle install --jobs 4 --retry 3

      # 5️⃣ Build the Jekyll site
      - run: bundle exec jekyll build -d ./_site

      # 6️⃣ Deploy the _site folder to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: false

